### ISSUE TITLE
Unable to download any dataset.

### ISSUE THREAD

**Issue by Sadam1195** [imdatceleste/m-ailabs-dataset#3]
First of all a big thank you for making these dataset public, great work indeed. 

I have been trying to download dataset from the site not sure if this is related to Fastly being the culprit but downloading link redirects to page not found and loads `This is somewhat embarrassing, isn’t it?`

while with wget I am getting this error.

```
wget http://www.caito.de/data/Training/stt_tts/de_DE.tgz
--2021-06-09 15:24:47--  http://www.caito.de/data/Training/stt_tts/de_DE.tgz
Resolving www.caito.de (www.caito.de)... 82.135.63.202
Connecting to www.caito.de (www.caito.de)|82.135.63.202|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.caito.de/data/Training/stt_tts/de_DE.tgz [following]
--2021-06-09 15:25:35--  https://www.caito.de/data/Training/stt_tts/de_DE.tgz
Connecting to www.caito.de (www.caito.de)|82.135.63.202|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-06-09 15:26:00 ERROR 404: Not Found.
```

@imdatsolak

**Comment by i-celeste-aurora** [comment]
Apologies for this, I have moved the data to a new server but did not expect people to use direct links, instead hoping they come over the web-page. Thus, I had forgotten to add a `Redirect 301` to the new location.

This is done now and you should be able to download them.

The direct link, in case redirect doesn't work is: replace `https://ww.caito.de/` with `https://data.solak.de/`

Sorry for the inconvenience.
